### ISSUE TITLE
Weird looking text 

### ISSUE THREAD

**Issue by SokoleFN** [Ubuntufanboy/bad-apple#6]
Dont work on xfce terminal

**Comment by Ubuntufanboy** [comment]
I am almost certain the problem is that the window size is not set correctly. You can change this in ``convert.py``. I will work on a calibration script later but for now you can change the value. on this line ``image = image.resize((639,108))`` the number should be a bit different for everybody. I would find the size of your terminal and put the size in replacement of 639,108. 
![image](https://user-images.githubusercontent.com/82414370/204404714-b55826ab-3c49-43fc-b71e-523d4e20bb54.png)
This is an image showing what it looks like when the value is set incorrectly

**Comment by Debianfanboy** [comment]
Version 1.2 fixes this issue!

**Comment by Ubuntufanboy** [comment]
If you have this issue, please update to Version 1.2
